default: &default
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  database_username: <%= ENV['DATABASE_USER'] %>
  database_password: <%= ENV['DATABASE_PASS'] %>
  database_host: <%= ENV['DATABASE_HOST'] %>
  email_user: <%= ENV['EMAIL_USER'] %>
  email_pass: <%= ENV['EMAIL_PASS'] %>

development:
  <<: *default
  database_name: cyber_vacations_development

test:
  <<: *default
  database_name: cyber_vacations_test

production:
  <<: *default
